=== maliit/plugins/maliit-keyboard/data/languages/VirtualKeyboardLayout.dtd
<!ELEMENT keyboard (layout | import)*>
<!ELEMENT import (symview | phonenumber | number)*>
<!ELEMENT symview EMPTY>
<!ELEMENT phonenumber EMPTY>
<!ELEMENT number EMPTY>
<!ELEMENT layout (section+)>
<!ELEMENT section (row+)>
<!ELEMENT row (key | spacer)*>
<!ELEMENT key (binding+)>
<!ELEMENT spacer EMPTY>
<!ELEMENT binding EMPTY>

<!ATTLIST keyboard
  version CDATA "1.0"
  title CDATA #IMPLIED
  language CDATA #IMPLIED
  catalog CDATA #IMPLIED
  autocapitalization (true | false) "true">

<!ATTLIST import
  file CDATA #IMPLIED>

<!ATTLIST symview
  src CDATA #REQUIRED>

<!ATTLIST phonenumber
  src CDATA #REQUIRED>

<!ATTLIST number
  src CDATA #REQUIRED>

<!ATTLIST layout
  type (general | url | email | number | phonenumber | common) "general"
  orientation (landscape | portrait) "landscape"
  uniform-font-size (true | false) "false"
>

<!ATTLIST section
  id CDATA #REQUIRED
  movable (true | false) "true"
  type (sloppy | non-sloppy) "sloppy"
  style CDATA #IMPLIED
>

<!ATTLIST row
  height (small | medium | large | x-large | xx-large) "medium"
>

<!ATTLIST key
  style (normal | special | deadkey) "normal"
  width (small | medium | large | x-large | xx-large | stretched) "medium"
  rtl (true | false) "false"
  id CDATA #IMPLIED
>

<!ATTLIST binding
  action (insert | shift | backspace | space | cycle | layout_menu | sym
          | return | commit | decimal_separator | plus_minus_toggle | switch
          | on_off_toggle | compose | left | up | right | down) "insert"
  shift (true|false) "false"
  alt (true|false) "false"
  label CDATA #IMPLIED
  secondary_label CDATA #IMPLIED
  accents CDATA #IMPLIED
  accented_labels CDATA #IMPLIED
  extended_labels CDATA #IMPLIED
  cycleset CDATA #IMPLIED
  dead (true | false) "false"
  quickpick (true | false) "false"
  rtl (true | false) "false"
  enlarge (true | false) "false"
>

=== maliit/plugins/maliit-keyboard/data/languages/el_gr.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Ελληνικά (EL)" version="1.0" catalog="el_gr" language="en_gr">
  <layout type="general">
    <section id="main" style="keys33"><!-- symview of this layout has only 33 keys, hence the style override -->
      <row>
        <key>
          <binding label=";"/>
          <binding shift="true" label=":"/>
        </key>
        <key>
          <binding label="ς"/>
          <binding shift="true" label="/"/>
        </key>
        <key>
          <binding label="ε" extended_labels="έ€" accented_labels="έ" accents="΄"/>
          <binding shift="true" label="Ε" extended_labels="Έ€" accented_labels="Έ" accents="΄"/>
        </key>
        <key>
          <binding label="ρ"/>
          <binding shift="true" label="Ρ"/>
        </key>
        <key>
          <binding label="τ"/>
          <binding shift="true" label="Τ"/>
        </key>
        <key>
          <binding label="υ" extended_labels="ύϋΰ" accented_labels="ύϋΰ" accents="΄¨΅"/>
          <binding shift="true" label="Υ" extended_labels="ΎΫ" accented_labels="ΎΫ" accents="΄¨"/>
        </key>
        <key>
          <binding label="θ"/>
          <binding shift="true" label="Θ"/>
        </key>
        <key>
          <binding label="ι" extended_labels="ίϊΐ" accented_labels="ίϊΐ" accents="΄¨΅"/>
          <binding shift="true" label="Ι" extended_labels="ΊΪ" accented_labels="ΊΪ" accents="΄¨"/>
        </key>
        <key>
          <binding label="ο" extended_labels="ό" accented_labels="ό" accents="΄"/>
          <binding shift="true" label="Ο" extended_labels="Ό" accented_labels="Ό" accents="΄"/>
        </key>
        <key>
          <binding label="π"/>
          <binding shift="true" label="Π"/>
        </key>
      </row>

      <row>
        <spacer/>

        <key>
          <binding label="α" extended_labels="ά" accented_labels="ά" accents="΄"/>
          <binding shift="true" label="Α" extended_labels="Ά" accented_labels="Ά" accents="΄"/>
        </key>
        <key>
          <binding label="σ" extended_labels="ς"/>
          <binding shift="true" label="Σ"/>
        </key>
        <key>
          <binding label="δ"/>
          <binding shift="true" label="Δ"/>
        </key>
        <key>
          <binding label="φ"/>
          <binding shift="true" label="Φ"/>
        </key>
        <key>
          <binding label="γ"/>
          <binding shift="true" label="Γ"/>
        </key>
        <key>
          <binding label="η" extended_labels="ή" accented_labels="ή" accents="΄"/>
          <binding shift="true" label="Η" extended_labels="Ή" accented_labels="Ή" accents="΄"/>
        </key>
        <key>
          <binding label="ξ"/>
          <binding shift="true" label="Ξ"/>
        </key>
        <key>
          <binding label="κ"/>
          <binding shift="true" label="Κ"/>
        </key>
        <key>
          <binding label="λ"/>
          <binding shift="true" label="Λ"/>
        </key>
        <key>
          <binding label="΄" dead="true" extended_labels="¨΅"/>
        </key>
        <spacer/>
      </row>

      <row>
        <key style="special" width="large">
          <binding action="shift"/>
        </key>

        <spacer/>

        <key>
          <binding label="ζ"/>
          <binding shift="true" label="Ζ"/>
        </key>
        <key>
          <binding label="χ"/>
          <binding shift="true" label="Χ"/>
        </key>
        <key>
          <binding label="ψ" />
          <binding shift="true" label="Ψ" />
        </key>
        <key>
          <binding label="ω" extended_labels="ώ" accented_labels="ώ" accents="΄"/>
          <binding shift="true" label="Ω" extended_labels="Ώ" accented_labels="Ώ" accents="΄"/>
        </key>
        <key>
          <binding label="β"/>
          <binding shift="true" label="Β"/>
        </key>
        <key>
          <binding label="ν"/>
          <binding shift="true" label="Ν"/>
        </key>
        <key>
          <binding label="μ"/>
          <binding shift="true" label="Μ"/>
        </key>

        <spacer/>

        <key style="special" width="large">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="?123"/>
        </key>

        <spacer/>

        <key id="emailUrlKey"><binding label=","/></key>
        <key width="xx-large"><binding action="space"/></key>
        <key><binding label="."/></key>

        <spacer/>

        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <import file="symbols_en.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/it.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Italiano" version="1.0" catalog="it" language="it">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="q"/>
          <binding shift="true" label="Q"/>
        </key>
        <key>
          <binding label="w"/>
          <binding shift="true" label="W"/>
        </key>
        <key>
          <binding accented_labels="è" accents="`" label="e" extended_labels="èéëê€"/>
          <binding shift="true" accented_labels="È" accents="`" label="E" extended_labels="ÈÉËÊ€"/>
        </key>
        <key>
          <binding label="r"/>
          <binding shift="true" label="R"/>
        </key>
        <key>
          <binding label="t"/>
          <binding shift="true" label="T"/>
        </key>
        <key>
          <binding label="y" extended_labels="¥"/>
          <binding shift="true" label="Y" extended_labels="¥"/>
        </key>
        <key>
          <binding accented_labels="ù" accents="`" label="u" extended_labels="ùüûú"/>
          <binding shift="true" accented_labels="Ù" accents="`" label="U" extended_labels="ÙÜÛÚ"/>
        </key>
        <key>
          <binding accented_labels="ì" accents="`" label="i" extended_labels="ìîïí"/>
          <binding shift="true" accented_labels="Ì" accents="`" label="I" extended_labels="ÌÎÏÍ"/>
        </key>
        <key>
          <binding accented_labels="ò" accents="`" label="o" extended_labels="òºóöôõø"/>
          <binding shift="true" accented_labels="Ò" accents="`" label="O" extended_labels="ÒºÓÖÔÕØ"/>
        </key>
        <key>
          <binding label="p"/>
          <binding shift="true" label="P"/>
        </key>
      </row>
      <row>
        <key>
          <binding accented_labels="à" accents="`" label="a" extended_labels="àªäáâã"/>
          <binding shift="true" accented_labels="À" accents="`" label="A" extended_labels="ÀªÄÁÂÃ"/>
        </key>
        <key>
          <binding label="s" extended_labels="ß$"/>
          <binding shift="true" label="S" extended_labels="$"/>
        </key>
        <key>
          <binding label="d"/>
          <binding shift="true" label="D"/>
        </key>
        <key>
          <binding label="f"/>
          <binding shift="true" label="F"/>
        </key>
        <key>
          <binding label="g"/>
          <binding shift="true" label="G"/>
        </key>
        <key>
          <binding label="h"/>
          <binding shift="true" label="H"/>
        </key>
        <key>
          <binding label="j"/>
          <binding shift="true" label="J"/>
        </key>
        <key>
          <binding label="k"/>
          <binding shift="true" label="K"/>
        </key>
        <key>
          <binding label="l"/>
          <binding shift="true" label="L"/>
        </key>
        <key><binding label="&#x0027;"/></key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="shift"/>
        </key>

        <key>
          <binding label="z"/>
          <binding shift="true" label="Z"/>
        </key>
        <key>
          <binding label="x"/>
          <binding shift="true" label="X"/>
        </key>
        <key>
          <binding label="c" extended_labels="ç"/>
          <binding shift="true" label="C" extended_labels="Ç"/>
        </key>
        <key>
          <binding label="v"/>
          <binding shift="true" label="V"/>
        </key>
        <key>
          <binding label="b"/>
          <binding shift="true" label="B"/>
        </key>
        <key>
          <binding label="n" extended_labels="ñ"/>
          <binding shift="true" label="N" extended_labels="Ñ"/>
        </key>
        <key>
          <binding label="m"/>
          <binding shift="true" label="M"/>
        </key>

        <key style="special" width="x-large">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="?123"/>
        </key>

        <key style="special">
          <binding dead="true" label="`"/>
        </key>
        <key id="emailUrlKey"><binding label=","/></key>

        <key width="stretched"><binding action="space"/></key>

        <key><binding label="."/></key>

        <key style="special" width="xx-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <import file="symbols-35.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/uk.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Українська" version="1.0" catalog="" language="uk">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="й"/>
          <binding shift="true" label="Й"/>
        </key>
        <key>
          <binding label="ц"/>
          <binding shift="true" label="Ц"/>
        </key>
        <key>
          <binding label="у"/>
          <binding shift="true" label="У"/>
        </key>
        <key>
          <binding label="к"/>
          <binding shift="true" label="К"/>
        </key>
        <key>
          <binding label="е"/>
          <binding shift="true" label="Е"/>
        </key>
        <key>
          <binding label="н"/>
          <binding shift="true" label="Н"/>
        </key>
        <key>
          <binding label="г"/>
          <binding shift="true" label="Г"/>
        </key>
        <key>
          <binding label="ш"/>
          <binding shift="true" label="Ш"/>
        </key>
        <key>
          <binding label="щ"/>
          <binding shift="true" label="Щ"/>
        </key>
        <key>
          <binding label="з"/>
          <binding shift="true" label="З"/>
        </key>
        <key>
          <binding label="х"/>
          <binding shift="true" label="Х"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="ф"/>
          <binding shift="true" label="Ф"/>
        </key>
        <key>
          <binding label="і"/>
          <binding shift="true" label="І"/>
        </key>
        <key>
          <binding label="в"/>
          <binding shift="true" label="В"/>
        </key>
        <key>
          <binding label="а"/>
          <binding shift="true" label="А"/>
        </key>
        <key>
          <binding label="п"/>
          <binding shift="true" label="П"/>
        </key>
        <key>
          <binding label="р"/>
          <binding shift="true" label="Р"/>
        </key>
        <key>
          <binding label="о"/>
          <binding shift="true" label="О"/>
        </key>
        <key>
          <binding label="л"/>
          <binding shift="true" label="Л"/>
        </key>
        <key>
          <binding label="д"/>
          <binding shift="true" label="Д"/>
        </key>
        <key>
          <binding label="ж"/>
          <binding shift="true" label="Ж"/>
        </key>
        <key>
          <binding label="є"/>
          <binding shift="true" label="Є"/>
        </key>
      </row>

      <row>
        <key style="special">
          <binding action="shift"/>
        </key>

        <key>
          <binding label="ґ"/>
          <binding shift="true" label="Ґ"/>
        </key>
        <key>
          <binding label="я"/>
          <binding shift="true" label="Я"/>
        </key>
        <key>
          <binding label="ч"/>
          <binding shift="true" label="Ч"/>
        </key>
        <key>
          <binding label="с"/>
          <binding shift="true" label="С"/>
        </key>
        <key>
          <binding label="м"/>
          <binding shift="true" label="М"/>
        </key>
        <key>
          <binding label="и"/>
          <binding shift="true" label="И"/>
        </key>
        <key>
          <binding label="т"/>
          <binding shift="true" label="Т"/>
        </key>
        <key>
          <binding label="ь"/>
          <binding shift="true" label="Ь"/>
        </key>
        <key>
          <binding label="б"/>
          <binding shift="true" label="Б"/>
        </key>

        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="large">
          <binding action="sym" label="?123"/>
        </key>

        <key>
          <binding label="ї"/>
          <binding shift="true" label="Ї"/>
        </key>
        <key id="emailUrlKey"><binding label=","/></key>

        <key width="xx-large">
          <binding action="space" label=""/>
        </key>

        <key><binding label="."/></key>
        <key>
          <binding label="ю"/>
          <binding shift="true" label="Ю"/>
        </key>

        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <import file="symbols_ru_uk.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/es.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Español" version="1.0" catalog="es" language="es">
  <layout type="general">
    <section id="main">
      <row>
      <key>
        <binding label="q"/>
        <binding shift="true" label="Q"/>
      </key>
      <key>
        <binding label="w"/>
        <binding shift="true" label="W"/>
      </key>
      <key>
        <binding accented_labels="éë" accents="´¨" label="e" extended_labels="éèêë€"/>
        <binding shift="true" accented_labels="ÉË" accents="´¨" label="E" extended_labels="ÉÈÊË€"/>
      </key>
      <key>
        <binding label="r"/>
        <binding shift="true" label="R"/>
      </key>
      <key>
        <binding label="t"/>
        <binding shift="true" label="T"/>
      </key>
      <key>
        <binding accented_labels="ÿ" accents="¨" label="y" extended_labels="¥"/>
        <binding shift="true" accented_labels="Ÿ" accents="¨" label="Y" extended_labels="¥"/>
      </key>
      <key>
        <binding accented_labels="úü" accents="´¨" label="u" extended_labels="úüùû"/>
        <binding shift="true" accented_labels="ÚÜ" accents="´¨" label="U" extended_labels="ÚÜÙÛ"/>
      </key>
      <key>
        <binding accented_labels="íï" accents="´¨" label="i" extended_labels="íïìî"/>
        <binding shift="true" accented_labels="ÍÏ" accents="´¨" label="I" extended_labels="ÍÏÌÎ"/>
      </key>
      <key>
        <binding accented_labels="óö" accents="´¨" label="o" extended_labels="óºöòôõ"/>
        <binding shift="true" accented_labels="ÓÖ" accents="´¨" label="O" extended_labels="ÓºÖÒÔÕ"/>
      </key>
      <key>
        <binding label="p"/>
        <binding shift="true" label="P"/>
      </key>
      </row>

      <row>
      <key>
        <binding accented_labels="áä" accents="´¨" label="a" extended_labels="áªäàâãæ"/>
        <binding shift="true" accented_labels="ÁÄ" accents="´¨" label="A" extended_labels="ÁªÄÀÂÃÆ"/>
      </key>
      <key>
        <binding label="s" extended_labels="ß$"/>
        <binding shift="true" label="S" extended_labels="$"/>
      </key>
      <key>
        <binding label="d"/>
        <binding shift="true" label="D"/>
      </key>
      <key>
        <binding label="f"/>
        <binding shift="true" label="F"/>
      </key>
      <key>
        <binding label="g"/>
        <binding shift="true" label="G"/>
      </key>
      <key>
        <binding label="h"/>
        <binding shift="true" label="H"/>
      </key>
      <key>
        <binding label="j"/>
        <binding shift="true" label="J"/>
      </key>
      <key>
        <binding label="k"/>
        <binding shift="true" label="K"/>
      </key>
      <key>
        <binding label="l" extended_labels="ŀ"/>
        <binding shift="true" label="L" extended_labels="Ŀ"/>
      </key>
      <key>
        <binding label="ñ"/>
        <binding shift="true" label="Ñ"/>
      </key>
      </row>

      <row>
      <key style="special" width="x-large">
        <binding action="shift" label=""/>
      </key>

      <key>
        <binding label="z"/>
        <binding shift="true" label="Z"/>
      </key>
      <key>
        <binding label="x"/>
        <binding shift="true" label="X"/>
      </key>
      <key>
        <binding label="c" extended_labels="ç"/>
        <binding shift="true" label="C" extended_labels="Ç"/>
      </key>
      <key>
        <binding label="v"/>
        <binding shift="true" label="V"/>
      </key>
      <key>
        <binding label="b"/>
        <binding shift="true" label="B"/>
      </key>
      <key>
        <binding label="n" extended_labels="ñ"/>
        <binding shift="true" label="N" extended_labels="Ñ"/>
      </key>
      <key>
        <binding label="m"/>
        <binding shift="true" label="M"/>
      </key>

      <key style="special" width="x-large">
        <binding action="backspace" label=""/>
      </key>
      
      </row>

      <row>
      <key style="special" width="x-large">
        <binding action="sym" label="?123"/>
      </key>

      <key style="special">
        <binding dead="true" label="´"/>
      </key>
      <key id="emailUrlKey"><binding label=","/></key>

      <key width="stretched">
        <binding action="space" label=""/>
      </key>

      <key><binding label="."/></key>

      <key style="special" width="xx-large" id="actionKey">
        <binding action="return" label=""/>
      </key>
      </row>
    </section>
  </layout>
  
  <import file="symbols-35.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/da.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Dansk" version="1.0" catalog="da" language="da">
  <layout type="general">
    <section id="main">
      <row>
      <key>
        <binding label="q"/>
        <binding shift="true" label="Q"/>
      </key>
      <key>
        <binding label="w"/>
        <binding shift="true" label="W"/>
      </key>
      <key>
        <binding label="e" extended_labels="éèëê€"/>
        <binding shift="true" label="E" extended_labels="ÉÈËÊ€"/>
      </key>
      <key>
        <binding label="r"/>
        <binding shift="true" label="R"/>
      </key>
      <key>
        <binding label="t" extended_labels="þ"/>
        <binding shift="true" label="T" extended_labels="Þ"/>
      </key>
      <key>
        <binding label="y" extended_labels="¥"/>
        <binding shift="true" label="Y" extended_labels="¥"/>
      </key>
      <key>
        <binding label="u" extended_labels="üùûú"/>
        <binding shift="true" label="U" extended_labels="ÜÙÛÚ"/>
      </key>
      <key>
        <binding label="i" extended_labels="îïìí"/>
        <binding shift="true" label="I" extended_labels="ÎÏÌÍ"/>
      </key>
      <key>
        <binding label="o" extended_labels="øöôòóõ"/>
        <binding shift="true" label="O" extended_labels="ØÖÔÒÓÕ"/>
      </key>
      <key>
        <binding label="p"/>
        <binding shift="true" label="P"/>
      </key>
      </row>

      <row>
      <key>
        <binding label="a" extended_labels="æåäàáâã"/>
        <binding shift="true" label="A" extended_labels="ÆÅÄÀÁÂÃ"/>
      </key>
      <key>
        <binding label="s" extended_labels="ß$"/>
        <binding shift="true" label="S" extended_labels="ß$"/>
      </key>
      <key>
        <binding label="d" extended_labels="ð"/>
        <binding shift="true" label="D" extended_labels="Ð"/>
      </key>
      <key>
        <binding label="f"/>
        <binding shift="true" label="F"/>
      </key>
      <key>
        <binding label="g"/>
        <binding shift="true" label="G"/>
      </key>
      <key>
        <binding label="h"/>
        <binding shift="true" label="H"/>
      </key>
      <key>
        <binding label="j"/>
        <binding shift="true" label="J"/>
      </key>
      <key>
        <binding label="k"/>
        <binding shift="true" label="K"/>
      </key>
      <key>
        <binding label="l"/>
        <binding shift="true" label="L"/>
      </key>
      <key>
        <binding label="å"/>
        <binding shift="true" label="Å"/>
      </key>
      </row>

      <row>
      <key style="special">
        <binding action="shift" label=""/>
      </key>

      <key>
        <binding label="z"/>
        <binding shift="true" label="Z"/>
      </key>
      <key>
        <binding label="x"/>
        <binding shift="true" label="X"/>
      </key>
      <key>
        <binding label="c" extended_labels="ç"/>
        <binding shift="true" label="C" extended_labels="Ç"/>
      </key>
      <key>
        <binding label="v"/>
        <binding shift="true" label="V"/>
      </key>
      <key>
        <binding label="b"/>
        <binding shift="true" label="B"/>
      </key>
      <key>
        <binding label="n" extended_labels="ñ"/>
        <binding shift="true" label="N" extended_labels="Ñ"/>
      </key>
      <key>
        <binding label="m"/>
        <binding shift="true" label="M"/>
      </key>
      <key>
        <binding label="æ" extended_labels="ä"/>
        <binding shift="true" label="Æ" extended_labels="Ä"/>
      </key>

      <key style="special">
        <binding action="backspace" label=""/>
      </key>
      </row>

      <row>
      <key style="special" width="large">
        <binding action="sym" label="?123"/>
      </key>

      <key id="emailUrlKey"><binding label=","/></key>
      <key><binding label="."/></key>

      <key width="xx-large">
        <binding action="space" label=""/>
      </key>

      <key>
        <binding label="ø" extended_labels="ö"/>
        <binding shift="true" label="Ø" extended_labels="Ö"/>
      </key>

      <key style="special" width="x-large" id="actionKey">
        <binding action="return" label=""/>
      </key>
    </row>
    </section>
  </layout>

  <import file="symbols-36-nordic.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/lib/languages/phonenumber_ru.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Phone Number" catalog="phonenumber">
  <layout type="phonenumber" orientation="landscape">
    <section id="main" movable="false" >
      <row height="x-large">
        <key>
          <binding label="1"/>
        </key>
        <key>
          <binding label="2" secondary_label="&#x0430;&#x0431;&#x0432;&#x0433;"/>
        </key>
        <key>
          <binding label="3" secondary_label="&#x0434;&#x0435;&#x0436;&#x0437;"/>
        </key>
        <key>
          <binding label="4" secondary_label="&#x0438;&#x0439;&#x043A;&#x043B;"/>
        </key>
        <key>
          <binding label="5" secondary_label="&#x043C;&#x043D;&#x043E;&#x043F;"/>
        </key>
        <key>
          <binding label="6" secondary_label="&#x0440;&#x0441;&#x0442;&#x0443;"/>
        </key>
        <key>
          <binding label="7" secondary_label="&#x0444;&#x0445;&#x0446;&#x0447;"/>
        </key>
        <key>
          <binding label="8" secondary_label="&#x0448;&#x0449;&#x044A;&#x044B;"/>
        </key>
        <key>
          <binding label="9" secondary_label="&#x044C;&#x044D;&#x044E;&#x044F;"/>
        </key>
        <key>
          <binding label="0"/>
        </key>
      </row>

      <row>
        <spacer/>

        <key width="large">
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key width="large">
          <binding label="&#x0023;"/>
        </key>
        <key style="special" width="large">
          <binding label="" action="backspace"/>
        </key>
        <key style="special" id="actionKey" width="large">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <layout type="phonenumber" orientation="portrait">
    <section id="main" movable="false" >
      <row>
        <key>
          <binding label="1"/>
        </key>
        <key>
          <binding label="2" secondary_label="&#x0430;&#x0431;&#x0432;&#x0433;"/>
        </key>
        <key>
          <binding label="3" secondary_label="&#x0434;&#x0435;&#x0436;&#x0437;"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="4" secondary_label="&#x0438;&#x0439;&#x043A;&#x043B;"/>
        </key>
        <key>
          <binding label="5" secondary_label="&#x043C;&#x043D;&#x043E;&#x043F;"/>
        </key>
        <key>
          <binding label="6" secondary_label="&#x0440;&#x0441;&#x0442;&#x0443;"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="7" secondary_label="&#x0444;&#x0445;&#x0446;&#x0447;"/>
        </key>
        <key>
          <binding label="8" secondary_label="&#x0448;&#x0449;&#x044A;&#x044B;"/>
        </key>
        <key>
          <binding label="9" secondary_label="&#x044C;&#x044D;&#x044E;&#x044F;"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key>
          <binding label="0"/>
        </key>
        <key>
          <binding label="&#x0023;"/>
        </key>
      </row>

      <row>
        <key style="special" width="large">
          <binding label="" action="backspace"/>
        </key>
        <spacer/>
        <key style="special" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>
