=== maliit/plugins/maliit-keyboard/data/languages/VirtualKeyboardLayout.dtd
<!ELEMENT keyboard (layout | import)*>
<!ELEMENT import (symview | phonenumber | number)*>
<!ELEMENT symview EMPTY>
<!ELEMENT phonenumber EMPTY>
<!ELEMENT number EMPTY>
<!ELEMENT layout (section+)>
<!ELEMENT section (row+)>
<!ELEMENT row (key | spacer)*>
<!ELEMENT key (binding+)>
<!ELEMENT spacer EMPTY>
<!ELEMENT binding EMPTY>

<!ATTLIST keyboard
  version CDATA "1.0"
  title CDATA #IMPLIED
  language CDATA #IMPLIED
  catalog CDATA #IMPLIED
  autocapitalization (true | false) "true">

<!ATTLIST import
  file CDATA #IMPLIED>

<!ATTLIST symview
  src CDATA #REQUIRED>

<!ATTLIST phonenumber
  src CDATA #REQUIRED>

<!ATTLIST number
  src CDATA #REQUIRED>

<!ATTLIST layout
  type (general | url | email | number | phonenumber | common) "general"
  orientation (landscape | portrait) "landscape"
  uniform-font-size (true | false) "false"
>

<!ATTLIST section
  id CDATA #REQUIRED
  movable (true | false) "true"
  type (sloppy | non-sloppy) "sloppy"
  style CDATA #IMPLIED
>

<!ATTLIST row
  height (small | medium | large | x-large | xx-large) "medium"
>

<!ATTLIST key
  style (normal | special | deadkey) "normal"
  width (small | medium | large | x-large | xx-large | stretched) "medium"
  rtl (true | false) "false"
  id CDATA #IMPLIED
>

<!ATTLIST binding
  action (insert | shift | backspace | space | cycle | layout_menu | sym
          | return | commit | decimal_separator | plus_minus_toggle | switch
          | on_off_toggle | compose | left | up | right | down) "insert"
  shift (true|false) "false"
  alt (true|false) "false"
  label CDATA #IMPLIED
  secondary_label CDATA #IMPLIED
  accents CDATA #IMPLIED
  accented_labels CDATA #IMPLIED
  extended_labels CDATA #IMPLIED
  cycleset CDATA #IMPLIED
  dead (true | false) "false"
  quickpick (true | false) "false"
  rtl (true | false) "false"
  enlarge (true | false) "false"
>

=== maliit/plugins/maliit-keyboard/data/languages/phonenumber_ar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Phone Number" catalog="phonenumber">
  <layout type="phonenumber" orientation="landscape">
    <section id="main" movable="false">
      <row height="x-large">
        <key>
          <binding label="&#x0661;"/>
        </key>
        <key>
          <binding label="&#x0662;" secondary_label="abc"/>
        </key>
        <key>
          <binding label="&#x0663;" secondary_label="def"/>
        </key>
        <key>
          <binding label="&#x0664;" secondary_label="ghi"/>
        </key>
        <key>
          <binding label="&#x0665;" secondary_label="jkl"/>
        </key>
        <key>
          <binding label="&#x0666;" secondary_label="mno"/>
        </key>
        <key>
          <binding label="&#x0667;" secondary_label="pqrs"/>
        </key>
        <key>
          <binding label="&#x0668;" secondary_label="tuv"/>
        </key>
        <key>
          <binding label="&#x0669;" secondary_label="wxyz"/>
        </key>
        <key>
          <binding label="&#x0660;"/>
        </key>
      </row>

      <row>
        <spacer/>

        <key width="large">
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key width="large">
          <binding label="&#x0023;"/>
        </key>
        <key style="special" width="large">
          <binding label="" action="backspace"/>
        </key>
        <key style="special" id="actionKey" width="large">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <layout type="phonenumber" orientation="portrait">
    <section id="main" movable="false">
      <row>
        <key>
          <binding label="&#x0661;"/>
        </key>
        <key>
          <binding label="&#x0662;" secondary_label="abc"/>
        </key>
        <key>
          <binding label="&#x0663;" secondary_label="def"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x0664;" secondary_label="ghi"/>
        </key>
        <key>
          <binding label="&#x0665;" secondary_label="jkl"/>
        </key>
        <key>
          <binding label="&#x0666;" secondary_label="mno"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x0667;" secondary_label="pqrs"/>
        </key>
        <key>
          <binding label="&#x0668;" secondary_label="tuv"/>
        </key>
        <key>
          <binding label="&#x0669;" secondary_label="wxyz"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key>
          <binding label="&#x0660;"/>
        </key>
        <key>
          <binding label="&#x0023;"/>
        </key>
      </row>

      <row>
        <key style="special" width="large">
          <binding label="" action="backspace"/>
        </key>
        <spacer/>
        <key style="special" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/te_in.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="తెలుగు (Telugu)" version="1.0" autocapitalization="false" catalog="te_in" language="te_in" >
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="ౌ"/>
          <binding shift="true" label="ఔ"/>
        </key>
        <key>
          <binding label="ై"/>
          <binding shift="true" label="ఐ"/>
        </key>
        <key>
          <binding label="ా"/>
          <binding shift="true" label="ఆ"/>
        </key>
        <key>
          <binding label="ీ"/>
          <binding shift="true" label="ఈ"/>
        </key>
        <key>
          <binding label="ూ"/>
          <binding shift="true" label="ఊ"/>
        </key>        
	<key>
          <binding label="బ"/>
          <binding shift="true" label="భ"/>
        </key>
        <key>
          <binding label="హ"/>
          <binding shift="true" label="ఙ"/>
        </key>
        <key>
          <binding label="గ"/>
          <binding shift="true" label="ఘ"/>
        </key>
        <key>
          <binding label="ద"/>
          <binding shift="true" label="ధ"/>
        </key>
        <key>
          <binding label="జ"/>
          <binding shift="true" label="ఝ"/>
        </key>
        <key>
          <binding label="డ"/>
          <binding shift="true" label="ఢ"/>
        </key>
      </row>
      <row>
        <key>
          <binding label="ో"/>
          <binding shift="true" label="ఓ"/>
        </key>
        <key>
          <binding label="ే"/>
          <binding shift="true" label="ఏ"/>
        </key>
        <key>
          <binding label="్"/>
          <binding shift="true" label="అ"/>
        </key>
        <key>
          <binding label="ి"/>
          <binding shift="true" label="ఇ"/>
        </key>
        <key>
          <binding label="ు"/>
          <binding shift="true" label="ఉ"/>
        </key>        
	<key>
          <binding label="ప"/>
          <binding shift="true" label="ఫ"/>
        </key>
        <key>
          <binding label="ర"/>
          <binding shift="true" label="ఱ"/>
        </key>
        <key>
          <binding label="క"/>
          <binding shift="true" label="ఖ"/>
        </key>
        <key>
          <binding label="త"/>
          <binding shift="true" label="థ"/>
        </key>
        <key>
          <binding label="చ"/>
          <binding shift="true" label="ఛ"/>
        </key>
        <key>
          <binding label="ట"/>
          <binding shift="true" label="ఠ"/>
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="shift"/>
        </key>
        <key>
          <binding label="ె"/>
          <binding shift="true" label="ఎ"/>
        </key>
        <key>
          <binding label="ం"/>
          <binding shift="true" label="ః"/>
        </key>
        <key>
          <binding label="మ"/>
          <binding shift="true" label="ణ"/>
        </key>
        <key>
          <binding label="న"/>
          <binding shift="true" label="ృ"/>
        </key>
        <key>
          <binding label="వ"/>
        </key>
        <key>
          <binding label="ల"/>
          <binding shift="true" label="ౕ"/>
        </key>
        <key>
          <binding label="స"/>
          <binding shift="true" label="శ"/>
        </key>
        <key>
          <binding label="య"/>
          <binding shift="true" label="ష"/>
        </key>
        <key style="special" width="x-large">
          <binding action="backspace"/>
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="+!="/>
        </key>
        <key>
          <binding label="ొ"/>
          <binding shift="true" label="ఒ"/>
        </key>
        <key>
          <binding label="ఞ"/>
        </key>
        <key style="special" width="stretched">
          <binding action="space"/>
        </key>
        <key>
          <binding label="ఁ"/>
          <binding shift="true" label="ౠ"/>
        </key>
        <key>
          <binding label="ౄ"/>
          <binding shift="true" label="ౡ"/>
        </key>
        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
    <section id="symbols0" type="non-sloppy">
      <row>
        <key>
          <binding label="౧"/>
          <binding shift="true" label="1"/>
       </key>
        <key>
          <binding label="౨"/>
          <binding shift="true" label="2"/>
        </key>
        <key>
          <binding label="౩"/>
          <binding shift="true" label="3"/>
        </key>
        <key>
          <binding label="౪"/>
          <binding shift="true" label="4"/>
        </key>
        <key>
          <binding label="౫"/>
          <binding shift="true" label="5"/>
        </key>
        <key>
          <binding label="౬"/>
          <binding shift="true" label="6"/>
        </key>
        <key>
          <binding label="౭"/>
          <binding shift="true" label="7 "/>
        </key>
        <key>
          <binding label="౮"/>
          <binding shift="true" label="8"/>
        </key>
        <key>
          <binding label="౯"/>
          <binding shift="true" label="9"/>
        </key>
        <key>
          <binding label="౦"/>
          <binding shift="true" label="0"/>
        </key>
        <key>
          <binding label="_"/>
        </key>
      </row>
      <row>
        <key>
          <binding label="൰"/>
        </key>
        <key>
          <binding label="&#x0022;"/>
        </key>
        <key>
          <binding label="&#x0027;"/>
        </key>
        <key>
          <binding label="{"/>
        </key>
        <key>
          <binding label="}"/>
        </key>
        <key>
          <binding label="?"/>
        </key>
        <key>
          <binding label=","/>
        </key>
        <key>
          <binding label="."/>
        </key>
        <key>
          <binding label="ఞ"/>
        </key>
        <key>
          <binding label="ఋ"/>
        </key>
        <key>
          <binding label="@"/>
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="shift"/>
        </key>
        <key>
          <binding label="%"/>
        </key>
        <key>
          <binding label="#"/>
        </key>
        <key>
          <binding label="("/>
        </key>
        <key>
          <binding label=")"/>
        </key>
        <key>
          <binding label="!"/>
        </key>
        <key>
          <binding label="£"/>
        </key>
        <key>
          <binding label="$"/>
        </key>
        <key>
          <binding label="₹"/>
        </key>
        <key style="special" width="x-large">
          <binding action="backspace"/>
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="అ"/>
        </key>
        <key>
          <binding label="="/>
         </key>
        <key>
          <binding label="+"/>
        </key>
        <key style="special" width="stretched">
          <binding action="space"/>
        </key>
        <key>
          <binding label="-"/>
        </key>
        <key>
          <binding label="*"/>
        </key>
        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/phonenumber_fa.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="Phone Number" catalog="phonenumber">
  <layout type="phonenumber" orientation="landscape">
    <section id="main" movable="false">
      <row height="x-large">
        <key>
          <binding label="&#x06F1;"/>
        </key>
        <key>
          <binding label="&#x06F2;" secondary_label="abc"/>
        </key>
        <key>
          <binding label="&#x06F3;" secondary_label="def"/>
        </key>
        <key>
          <binding label="&#x06F4;" secondary_label="ghi"/>
        </key>
        <key>
          <binding label="&#x06F5;" secondary_label="jkl"/>
        </key>
        <key>
          <binding label="&#x06F6;" secondary_label="mno"/>
        </key>
        <key>
          <binding label="&#x06F7;" secondary_label="pqrs"/>
        </key>
        <key>
          <binding label="&#x06F8;" secondary_label="tuv"/>
        </key>
        <key>
          <binding label="&#x06F9;" secondary_label="wxyz"/>
        </key>
        <key>
          <binding label="&#x06F0;"/>
        </key>
      </row>

      <row>
        <spacer/>

        <key width="large">
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key width="large">
          <binding label="&#x0023;"/>
        </key>
        <key style="special" width="large">
          <binding label="" action="backspace"/>
        </key>
        <key style="special" id="actionKey" width="large">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <layout type="phonenumber" orientation="portrait">
    <section id="main" movable="false">
      <row>
        <key>
          <binding label="&#x06F1;"/>
        </key>
        <key>
          <binding label="&#x06F2;" secondary_label="abc"/>
        </key>
        <key>
          <binding label="&#x06F3;" secondary_label="def"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x06F4;" secondary_label="ghi"/>
        </key>
        <key>
          <binding label="&#x06F5;" secondary_label="jkl"/>
        </key>
        <key>
          <binding label="&#x06F6;" secondary_label="mno"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x06F7;" secondary_label="pqrs"/>
        </key>
        <key>
          <binding label="&#x06F8;" secondary_label="tuv"/>
        </key>
        <key>
          <binding label="&#x06F9;" secondary_label="wxyz"/>
        </key>
      </row>

      <row> 
        <key>
          <binding label="&#x002A;&#x002B;" cycleset="&#x002A;&#x002B;p" action="cycle"/>
        </key>
        <key>
          <binding label="&#x06F0;"/>
        </key>
        <key>
          <binding label="&#x0023;"/>
        </key>
      </row>

      <row>
        <key style="special" width="large">
          <binding label="" action="backspace"/>
        </key>
        <spacer/>
        <key style="special" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/hu.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Magyar" version="1.0" catalog="hu" language="hu">
  <layout type="general">
    <section id="main">
      <row>
       <key>
        <binding label="q"/>
        <binding shift="true" label="Q"/>
       </key>
       <key>
        <binding label="w"/>
        <binding shift="true" label="W"/>
       </key>
       <key>
        <binding accented_labels="é" accents="´" label="e" extended_labels="éęě€"/>
        <binding shift="true" accented_labels="É" accents="´" label="E" extended_labels="ÉĘĚ€"/>
       </key>
       <key>
        <binding label="r" extended_labels="ŕř"/>
        <binding shift="true" label="R" extended_labels="ŔŘ"/>
       </key>
       <key>
        <binding label="t" extended_labels="ţť"/>
        <binding shift="true" label="T" extended_labels="ŢŤ"/>
       </key>
       <key>
        <binding label="z" extended_labels="źżž"/>
        <binding shift="true" label="Z" extended_labels="ŹŻŽ"/>
       </key>
       <key>
        <binding accented_labels="úüű" accents="´¨˝" label="u" extended_labels="úüűů"/>
        <binding shift="true" accented_labels="ÚÜŰ" accents="´¨˝" label="U" extended_labels="ÚÜŰŮ"/>
       </key>
       <key>
        <binding accented_labels="í" accents="´" label="i" extended_labels="íî"/>
        <binding shift="true" accented_labels="Í" accents="´" label="I" extended_labels="ÍÎ"/>
       </key>
       <key>
        <binding accented_labels="óöő" accents="´¨˝" label="o" extended_labels="óöőô"/>
        <binding shift="true" accented_labels="ÓÖŐ" accents="´¨˝" label="O" extended_labels="ÓÖŐÔ"/>
       </key>
       <key>
        <binding label="p"/>
        <binding shift="true" label="P"/>
       </key>
      </row>

      <row>
       <key>
        <binding accented_labels="á" accents="´" label="a" extended_labels="áäâăą"/>
        <binding shift="true" accented_labels="Á" accents="´" label="A" extended_labels="ÁÄÂĂĄ"/>
       </key>
       <key>
        <binding label="s" extended_labels="ßśşš$"/>
        <binding shift="true" label="S" extended_labels="ŚŞŠ$"/>
       </key>
       <key>
        <binding label="d" extended_labels="đď"/>
        <binding shift="true" label="D" extended_labels="ĐĎ"/>
       </key>
       <key>
        <binding label="f"/>
        <binding shift="true" label="F"/>
       </key>
       <key>
        <binding label="g"/>
        <binding shift="true" label="G"/>
       </key>
       <key>
        <binding label="h"/>
        <binding shift="true" label="H"/>
       </key>
       <key>
        <binding label="j"/>
        <binding shift="true" label="J"/>
       </key>
       <key>
        <binding label="k"/>
        <binding shift="true" label="K"/>
       </key>
       <key>
        <binding label="l"/>
        <binding shift="true" label="L"/>
       </key>
       <key style="special">
        <binding dead="true" label="&#x00B4;"/>
       </key>
      </row>

      <row>
       <key style="special">
        <binding action="shift" label=""/>
       </key>

       <key>
        <binding label="y" extended_labels="¥"/>
        <binding shift="true" label="Y" extended_labels="¥"/>
       </key>
       <key>
        <binding label="x"/>
        <binding shift="true" label="X"/>
       </key>
       <key>
        <binding label="c" extended_labels="ćčç"/>
        <binding shift="true" label="C" extended_labels="ĆČÇ"/>
       </key>
       <key>
        <binding label="v"/>
        <binding shift="true" label="V"/>
       </key>
       <key>
        <binding label="b"/>
        <binding shift="true" label="B"/>
       </key>
       <key>
        <binding label="n" extended_labels="ńňñ"/>
        <binding shift="true" label="N" extended_labels="ŃŇÑ"/>
       </key>
       <key>
        <binding label="m"/>
        <binding shift="true" label="M"/>
       </key>
       <key style="special">
        <binding dead="true" label="&#x02DD;"/>
       </key>

       <key style="special">
        <binding action="backspace" label=""/>
       </key>
      </row>

      <row>
       <key style="special" width="large">
        <binding action="sym" label="?123"/>
       </key>

       <key style="special"><binding dead="true" label="¨"/></key>
       <key id="emailUrlKey"><binding label=","/></key>

       <key width="xx-large">
        <binding action="space" label=""/>
       </key>

       <key><binding label="."/></key>

       <key style="special" width="x-large" id="actionKey">
        <binding action="return" label=""/>
       </key>
      </row>
    </section>
  </layout>

  <import file="symbols-36.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/ru.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Русский" version="1.0" catalog="ru" language="ru">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="й"/>
          <binding shift="true" label="Й"/>
        </key>
        <key>
          <binding label="ц"/>
          <binding shift="true" label="Ц"/>
        </key>
        <key>
          <binding label="у" extended_labels="ў"/>
          <binding shift="true" label="У" extended_labels="Ў"/>
        </key>
        <key>
          <binding label="к"/>
          <binding shift="true" label="К"/>
        </key>
        <key>
          <binding label="е" extended_labels="ё€"/>
          <binding shift="true" label="Е" extended_labels="Ё€"/>
        </key>
        <key>
          <binding label="н"/>
          <binding shift="true" label="Н"/>
        </key>
        <key>
          <binding label="г"/>
          <binding shift="true" label="Г"/>
        </key>
        <key>
          <binding label="ш"/>
          <binding shift="true" label="Ш"/>
        </key>
        <key>
          <binding label="щ"/>
          <binding shift="true" label="Щ"/>
        </key>
        <key>
          <binding label="з"/>
          <binding shift="true" label="З"/>
        </key>
        <key>
          <binding label="х"/>
          <binding shift="true" label="Х"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="ф"/>
          <binding shift="true" label="Ф"/>
        </key>
        <key>
          <binding label="ы"/>
          <binding shift="true" label="Ы"/>
        </key>
        <key>
          <binding label="в"/>
          <binding shift="true" label="В"/>
        </key>
        <key>
          <binding label="а"/>
          <binding shift="true" label="А"/>
        </key>
        <key>
          <binding label="п"/>
          <binding shift="true" label="П"/>
        </key>
        <key>
          <binding label="р"/>
          <binding shift="true" label="Р"/>
        </key>
        <key>
          <binding label="о"/>
          <binding shift="true" label="О"/>
        </key>
        <key>
          <binding label="л"/>
          <binding shift="true" label="Л"/>
        </key>
        <key>
          <binding label="д"/>
          <binding shift="true" label="Д"/>
        </key>
        <key>
          <binding label="ж"/>
          <binding shift="true" label="Ж"/>
        </key>
        <key>
          <binding label="э"/>
          <binding shift="true" label="Э"/>
        </key>
      </row>

      <row>
        <key style="special">
          <binding action="shift" label=""/>
        </key>

        <key>
          <binding label="я"/>
          <binding shift="true" label="Я"/>
        </key>
        <key>
          <binding label="ч"/>
          <binding shift="true" label="Ч"/>
        </key>
        <key>
          <binding label="с"/>
          <binding shift="true" label="С"/>
        </key>
        <key>
          <binding label="м"/>
          <binding shift="true" label="М"/>
        </key>
        <key>
          <binding label="и" extended_labels="і"/>
          <binding shift="true" label="И" extended_labels="І"/>
        </key>
        <key>
          <binding label="т"/>
          <binding shift="true" label="Т"/>
        </key>
        <key>
          <binding label="ь"/>
          <binding shift="true" label="Ь"/>
        </key>
        <key>
          <binding label="б"/>
          <binding shift="true" label="Б"/>
        </key>
        <key>
          <binding label="ю"/>
          <binding shift="true" label="Ю"/>
        </key>

        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="large">
          <binding action="sym" label="?123"/>
        </key>

        <key><binding label="-"/></key>
        <key id="emailUrlKey"><binding label=","/></key>

        <key width="xx-large">
          <binding action="space" label=""/>
        </key>

        <key><binding label="."/></key>
        <key>
          <binding label="ъ"/>
          <binding shift="true" label="Ъ"/>
        </key>

        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <import file="symbols_ru_uk.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/symbols_vi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" catalog="symbols">
  <layout type="general">
    <section id="symbols0" type="non-sloppy" style="vietnamese">
      <row>
        <key>
           <binding label="1"/>
        </key>
        <key>
           <binding label="2"/>
        </key>
        <key>
           <binding label="3"/>
        </key>
        <key>
           <binding label="4"/>
        </key>
        <key>
           <binding label="5"/>
        </key>
        <key>
          <binding label="6"/>
        </key>
        <key>
          <binding label="7"/>
        </key>
        <key>
          <binding label="8"/>
        </key>
        <key>
          <binding label="9"/>
        </key>
        <key>
          <binding label="0"/>
        </key>
        <key>
          <binding label="%"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="*"/>
        </key>
        <key>
          <binding label="#"/>
        </key>
        <key>
          <binding label="+"/>
        </key>
        <key>
          <binding label="-"/>
        </key>
        <key>
          <binding label="="/>
        </key>
        <key>
          <binding label="("/>
        </key>
        <key>
          <binding label=")"/>
        </key>
        <key>
          <binding label="["/>
        </key>
        <key>
          <binding label="]"/>
        </key>
        <key>
          <binding label="!"/>
        </key>
        <key>
          <binding label="?"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="@" quickpick="true"/>
        </key>
        <key>
          <binding label="~"/>
        </key>
        <key>
          <binding label="/"/>
        </key>
        <key>
          <binding label="\"/>
        </key>
        <key>
          <binding label="_"/>
        </key>
        <key>
          <binding label="&#x0027;" quickpick="true"/>
        </key>
        <key>
          <binding label="&#x0022;"/>
        </key>
        <key>
          <binding label="&#x0026;"/>
        </key>
        <key>
          <binding label="§"/>
        </key>
        <key>
          <binding label="&lt;"/>
        </key>
        <key>
          <binding label="&gt;"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="`"/>
        </key>
        <key>
          <binding label="^"/>
        </key>
        <key>
          <binding label="|"/>
        </key>
        <key>
          <binding label="€"/>
        </key>
        <key>
          <binding label="£"/>
        </key>
        <key>
          <binding label="$"/>
        </key>
        <key>
          <binding label="¥"/>
        </key>
        <key>
          <binding label="₫"/>
        </key>
        <key>
          <binding label=";"/>
        </key>
        <key>
          <binding label=":"/>
        </key>

        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="ABC"/>
        </key>

        <spacer/>

        <key><binding label=","/></key>
        <key width="stretched"><binding action="space"/></key>
        <key><binding label="."/></key>

        <spacer/>

        <key style="special" width="xx-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>
