=== maliit/plugins/maliit-keyboard/data/languages/VirtualKeyboardLayout.dtd
<!ELEMENT keyboard (layout | import)*>
<!ELEMENT import (symview | phonenumber | number)*>
<!ELEMENT symview EMPTY>
<!ELEMENT phonenumber EMPTY>
<!ELEMENT number EMPTY>
<!ELEMENT layout (section+)>
<!ELEMENT section (row+)>
<!ELEMENT row (key | spacer)*>
<!ELEMENT key (binding+)>
<!ELEMENT spacer EMPTY>
<!ELEMENT binding EMPTY>

<!ATTLIST keyboard
  version CDATA "1.0"
  title CDATA #IMPLIED
  language CDATA #IMPLIED
  catalog CDATA #IMPLIED
  autocapitalization (true | false) "true">

<!ATTLIST import
  file CDATA #IMPLIED>

<!ATTLIST symview
  src CDATA #REQUIRED>

<!ATTLIST phonenumber
  src CDATA #REQUIRED>

<!ATTLIST number
  src CDATA #REQUIRED>

<!ATTLIST layout
  type (general | url | email | number | phonenumber | common) "general"
  orientation (landscape | portrait) "landscape"
  uniform-font-size (true | false) "false"
>

<!ATTLIST section
  id CDATA #REQUIRED
  movable (true | false) "true"
  type (sloppy | non-sloppy) "sloppy"
  style CDATA #IMPLIED
>

<!ATTLIST row
  height (small | medium | large | x-large | xx-large) "medium"
>

<!ATTLIST key
  style (normal | special | deadkey) "normal"
  width (small | medium | large | x-large | xx-large | stretched) "medium"
  rtl (true | false) "false"
  id CDATA #IMPLIED
>

<!ATTLIST binding
  action (insert | shift | backspace | space | cycle | layout_menu | sym
          | return | commit | decimal_separator | plus_minus_toggle | switch
          | on_off_toggle | compose | left | up | right | down) "insert"
  shift (true|false) "false"
  alt (true|false) "false"
  label CDATA #IMPLIED
  secondary_label CDATA #IMPLIED
  accents CDATA #IMPLIED
  accented_labels CDATA #IMPLIED
  extended_labels CDATA #IMPLIED
  cycleset CDATA #IMPLIED
  dead (true | false) "false"
  quickpick (true | false) "false"
  rtl (true | false) "false"
  enlarge (true | false) "false"
>

=== maliit/plugins/maliit-keyboard/data/languages/symbols_fa.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" catalog="symbols">
  <layout type="general">
    <section id="symbols0" type="non-sloppy">
      <row>
        <key>
          <binding label="&#x06F1;"/>
        </key>
        <key>
          <binding label="&#x06F2;"/>
        </key>
        <key>
          <binding label="&#x06F3;"/>
        </key>
        <key>
          <binding label="&#x06F4;"/>
        </key>
        <key>
          <binding label="&#x06F5;"/>
        </key>
        <key>
          <binding label="&#x06F6;"/>
        </key>
        <key>
          <binding label="&#x06F7;"/>
        </key>
        <key>
          <binding label="&#x06F8;"/>
        </key>
        <key>
          <binding label="&#x06F9;"/>
        </key>
        <key>
          <binding label="&#x06F0;"/>
        </key>
        <key>
          <binding label="٪"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="*"/>
        </key>
        <key>
          <binding label="#"/>
        </key>
        <key>
          <binding label="+"/>
        </key>
        <key>
          <binding label="-"/>
        </key>
        <key>
          <binding label="_"/>
        </key>
        <key>
          <binding label="="/>
        </key>
        <key>
          <binding label="&#x0026;"/>
        </key>
        <key>
          <binding label=")" rtl="true"/>
        </key>
        <key>
          <binding label="(" rtl="true"/>
        </key>
        <key>
          <binding label="&gt;" rtl="true"/>
        </key>
        <key>
          <binding label="&lt;" rtl="true"/>
        </key>
      </row>

      <row>
        <key style="special">
          <binding action="switch" label="&#x0662;/&#x0661;"/>
        </key>
        <key>
          <binding label="@" quickpick="true"/>
        </key>
        <key>
          <binding label="~"/>
        </key>
        <key>
          <binding label="/"/>
        </key>
        <key>
          <binding label="\"/>
        </key>
        <key>
          <binding label="&#x0027;" quickpick="true"/>
        </key>
        <key>
          <binding label="&#x066B;"/>
        </key>
        <key>
          <binding label="&#x066C;"/>
        </key>
        <key>
          <binding label="!"/>
        </key>
        <key>
          <binding label="&#x061F;"/>
        </key>
        
        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="&#x0627;&#x200C;&#x0628;&#x200C;&#x067E;"/>
        </key>
        <key><binding label="&#x061B;"/></key>
        <key><binding label="&#x060C;"/></key>
        
        <key width="stretched">
          <binding action="space"/>
        </key>
        
        <key><binding label="&#x002E;"/></key>
        <key><binding label="&#x003A;"/></key>
        
        <key style="special" width="xx-large" id="actionKey">
          <binding action="return"/>
        </key>

      </row>
    </section>

    <section id="symbols1" type="non-sloppy">
      <row>
        <key>
          <binding label="1"/>
        </key>
        <key>
          <binding label="2"/>
        </key>
        <key>
          <binding label="3"/>
        </key>
        <key>
          <binding label="4"/>
        </key>
        <key>
          <binding label="5"/>
        </key>
        <key>
          <binding label="6"/>
        </key>
        <key>
          <binding label="7"/>
        </key>
        <key>
          <binding label="8"/>
        </key>
        <key>
          <binding label="9"/>
        </key>
        <key>
          <binding label="0"/>
        </key>
        <key>
          <binding label="%"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="€"/>
        </key>
        <key>
          <binding label="£"/>
        </key>
        <key>
          <binding label="$"/>
        </key>
        <key>
          <binding label="¥"/>
        </key>
        <key>
          <binding label="&#1585;&#1740;&#1575;&#1604;" rtl="true"/>
        </key>
        <key>
          <binding label="&#x007D;" rtl="true"/>
        </key>
        <key>
          <binding label="&#x007B;" rtl="true"/>
        </key>
        <key>
          <binding label="&#x005D;" rtl="true"/>
        </key>
        <key>
          <binding label="&#x005B;" rtl="true"/>
        </key>
        <key>
          <binding label="&#x00BB;" rtl="true"/>
        </key>
        <key>
          <binding label="&#x00AB;" rtl="true"/>
        </key>
      </row>

      <row>
        <key style="special">
          <binding action="switch" label="&#x0662;/&#x0662;"/>
        </key>
        <key>
          <binding label="&#x0060;"/>
        </key>
        <key>
          <binding label="&#x005E;"/>
        </key>
        <key>
          <binding label="&#x007C;"/>
        </key>
        <key>
          <binding label="‰"/>
        </key>
        <key>
          <binding label="&#x0022;"/>
        </key>
        <key>
          <binding label="&#x201C;"/>
        </key>
        <key>
          <binding label="&#x201D;"/>
        </key>
        <key>
          <binding label="&#x201E;"/>
        </key>
        <key>
          <binding label="?"/>
        </key>

        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="&#x0627;&#x200C;&#x0628;&#x200C;&#x067E;"/>
        </key>
        
        <key><binding label=";"/></key>
        <key><binding label="&#x002C;"/></key>
        
        <key width="stretched">
          <binding action="space"/>
        </key>
	<key><binding label="."/></key>
        <key><binding label=":"/></key>
        
        <key style="special" width="xx-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/cs.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Čeština" version="1.0" catalog="cs" language="cs">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="q"/>
          <binding shift="true" label="Q"/>
        </key>
        <key>
          <binding label="w"/>
          <binding shift="true" label="W"/>
        </key>
        <key>
          <binding extended_labels="ěéę€" accented_labels="éě" accents="´ˇ" label="e"/>
          <binding extended_labels="ĚÉĘ€" shift="true" accented_labels="ÉĚ" accents="´ˇ" label="E"/>
        </key>
        <key>
          <binding extended_labels="řŕ" accented_labels="ř" accents="ˇ" label="r"/>
          <binding extended_labels="ŘŔ" shift="true" accented_labels="Ř" accents="ˇ" label="R"/>
        </key>
        <key>
          <binding extended_labels="ťţ" accented_labels="ť" accents="ˇ" label="t"/>
          <binding extended_labels="ŤŢ" shift="true" accented_labels="Ť" accents="ˇ" label="T"/>
        </key>
        <key>
          <binding extended_labels="žźż" accented_labels="ž" accents="ˇ" label="z"/>
          <binding extended_labels="ŽŹŻ" shift="true" accented_labels="Ž" accents="ˇ" label="Z"/>
        </key>
        <key>
          <binding extended_labels="ůúüűùû" accented_labels="ú" accents="´" label="u"/>
          <binding extended_labels="ŮÚÜŰÙÛ" shift="true" accented_labels="Ú" accents="´" label="U"/>
        </key>
        <key>
          <binding extended_labels="íî" accented_labels="í" accents="´" label="i"/>
          <binding extended_labels="ÍÎ" shift="true" accented_labels="Í" accents="´" label="I"/>
        </key>
        <key>
          <binding extended_labels="óöőô" accented_labels="ó" accents="´" label="o"/>
          <binding extended_labels="ÓÖŐÔ" shift="true" accented_labels="Ó" accents="´" label="O"/>
        </key>
        <key>
          <binding label="p"/>
          <binding shift="true" label="P"/>
        </key>
      </row>

      <row>
        <key>
          <binding extended_labels="áäăâą" accented_labels="á" accents="´" label="a"/>
          <binding extended_labels="ÁÄĂÂĄ" shift="true" accented_labels="Á" accents="´" label="A"/>
        </key>
        <key>
          <binding extended_labels="šßśş$" accented_labels="š" accents="ˇ" label="s"/>
          <binding extended_labels="ŠŚŞ$" shift="true" accented_labels="Š" accents="ˇ" label="S"/>
        </key>
        <key>
          <binding extended_labels="ďđ" accented_labels="ď" accents="ˇ" label="d"/>
          <binding extended_labels="ĎĐ" shift="true" accented_labels="Ď" accents="ˇ" label="D"/>
        </key>
        <key>
          <binding label="f"/>
          <binding shift="true" label="F"/>
        </key>
        <key>
          <binding label="g"/>
          <binding shift="true" label="G"/>
        </key>
        <key>
          <binding label="h"/>
          <binding shift="true" label="H"/>
        </key>
        <key>
          <binding label="j"/>
          <binding shift="true" label="J"/>
        </key>
        <key>
          <binding label="k"/>
          <binding shift="true" label="K"/>
        </key>
        <key>
          <binding extended_labels="ľĺł" label="l"/>
          <binding extended_labels="ĽĹŁ" shift="true" label="L"/>
        </key>
		<key style="special">
            <binding dead="true" label="´"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="shift" label=""/>
        </key>

        <key>
          <binding extended_labels="ý¥" accented_labels="ý" accents="´" label="y"/>
          <binding extended_labels="Ý¥" shift="true" accented_labels="Ý" accents="´" label="Y"/>
        </key>
        <key>
          <binding label="x"/>
          <binding shift="true" label="X"/>
        </key>
        <key>
          <binding extended_labels="čćç" accented_labels="č" accents="ˇ" label="c"/>
          <binding extended_labels="ČĆÇ" shift="true" accented_labels="Č" accents="ˇ" label="C"/>
        </key>
        <key>
          <binding label="v"/>
          <binding shift="true" label="V"/>
        </key>
        <key>
          <binding label="b"/>
          <binding shift="true" label="B"/>
        </key>
        <key>
          <binding extended_labels="ňńñ" accented_labels="ň" accents="ˇ" label="n"/>
          <binding extended_labels="ŇŃÑ" shift="true" accented_labels="Ň" accents="ˇ" label="N"/>
        </key>
        <key>
          <binding label="m"/>
          <binding shift="true" label="M"/>
        </key>

        <key style="special" width="x-large">
          <binding action="backspace" label=""/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="?123"/>
        </key>

        <key style="special">
          <binding dead="true" label="ˇ"/>
        </key>
        <key id="emailUrlKey"><binding label=","/></key>

        <key width="stretched">
          <binding action="space" label=""/>
        </key>

        <key><binding label="."/></key>

        <key style="special" width="xx-large" id="actionKey">
          <binding action="return" label=""/>
        </key>
      </row>

    </section>
  </layout>

  <import file="symbols-35.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/mk_mk.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="Македонски" version="1.0" catalog="mk_mk" language="mk_mk">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="љ"/>
          <binding shift="true" label="Љ"/>
        </key>
        <key>
          <binding label="њ"/>
          <binding shift="true" label="Њ"/>
        </key>
        <key>
          <binding label="е" extended_labels="è€"/>
          <binding shift="true" label="Е" extended_labels="È€"/>
        </key>
        <key>
          <binding label="р"/>
          <binding shift="true" label="Р"/>
        </key>
        <key>
          <binding label="т" />
          <binding shift="true" label="Т" />
        </key>
        <key>
          <binding label="ѕ"/>
          <binding shift="true" label="Ѕ"/>
        </key>
        <key>
          <binding label="у"/>
          <binding shift="true" label="У"/>
        </key>
        <key>
          <binding label="и" extended_labels="ѝ"/>
          <binding shift="true" label="И" extended_labels="ѝ"/>
        </key>
        <key>
          <binding label="о"/>
          <binding shift="true" label="O"/>
        </key>
        <key>
          <binding label="п"/>
          <binding shift="true" label="П"/>
        </key>
        <key>
          <binding label="ш"/>
          <binding shift="true" label="Ш"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="а" />
          <binding shift="true" label="А" />
        </key>
        <key>
          <binding label="с" extended_labels="$"/>
          <binding shift="true" label="С" extended_labels="$"/>
        </key>
        <key>
          <binding label="д" />
          <binding shift="true" label="Д" />
        </key>
        <key>
          <binding label="ф"/>
          <binding shift="true" label="Ф"/>
        </key>
        <key>
          <binding label="г"/>
          <binding shift="true" label="Г"/>
        </key>
        <key>
          <binding label="х"/>
          <binding shift="true" label="Х"/>
        </key>
        <key>
          <binding label="ј"/>
          <binding shift="true" label="Ј"/>
        </key>
        <key>
          <binding label="к"/>
          <binding shift="true" label="К"/>
        </key>
        <key>
          <binding label="л"/>
          <binding shift="true" label="Л"/>
        </key>
        <key>
          <binding label="ч"/>
          <binding shift="true" label="Ч"/>
        </key>
        <key>
          <binding label="ќ"/>
          <binding shift="true" label="Ќ"/>
        </key>
      </row>

      <row>
        <key style="special">
          <binding action="shift"/>
        </key>

        <key>
          <binding label="з"/>
          <binding shift="true" label="З"/>
        </key>
        <key>
          <binding label="џ"/>
          <binding shift="true" label="Џ"/>
        </key>
        <key>
          <binding label="ц"/>
          <binding shift="true" label="Ц"/>
        </key>
        <key>
          <binding label="в"/>
          <binding shift="true" label="В"/>
        </key>
        <key>
          <binding label="б"/>
          <binding shift="true" label="Б"/>
        </key>
        <key>
          <binding label="н"/>
          <binding shift="true" label="Н"/>
        </key>
        <key>
          <binding label="м"/>
          <binding shift="true" label="М"/>
        </key>
        <key>
          <binding label="ѓ"/>
          <binding shift="true" label="Ѓ"/>
        </key>
        <key>
          <binding label="ж"/>
          <binding shift="true" label="Ж"/>
        </key>


        <key style="special">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="?123"/>
        </key>

        <spacer/>

        <key><binding label=";"/></key>
        <key id="emailUrlKey"><binding label=","/></key>
        <key width="xx-large"><binding action="space"/></key>
        <key><binding label="."/></key>
        <key><binding label=":"/></key>

        <spacer/>

        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <import file="symbols_ru_uk.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/ar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard version="1.0" title="العربية" language="ar" catalog="ar" autocapitalization="false">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="ض"/>
        </key>
        <key>
          <binding label="ص"/>
        </key>
        <key>
          <binding label="ث"/>
        </key>
        <key>
          <binding label="ق"/>
        </key>
        <key>
          <binding label="ف"/>
        </key>
        <key>
          <binding label="غ"/>
          <binding shift="true" label="إ"/>
        </key>
        <key>
          <binding label="ع"/>
        </key>
        <key>
          <binding label="ه"/>
        </key>
        <key>
          <binding label="خ"/>
        </key>
        <key>
          <binding label="ح"/>
        </key>
        <key>
          <binding label="ج"/>
        </key>
      </row>

      <row>
        <key>
          <binding label="ش"/>
        </key>
        <key>
          <binding label="س"/>
        </key>
        <key>
          <binding label="ي"/>
        </key>
        <key>
          <binding label="ب"/>
        </key>
        <key>
          <binding label="ل"/>
        </key>
        <key>
          <binding label="ا"/>
          <binding shift="true" label="أ"/>
        </key>
        <key>
          <binding label="ت"/>
        </key>
        <key>
          <binding label="ن"/>
        </key>
        <key>
          <binding label="م"/>
        </key>
        <key>
          <binding label="ك"/>
        </key>
        <key>
          <binding label="د"/>
        </key>
      </row>
	
      <row>
        <key style="special">
          <binding action="shift"/>
        </key>

        <key>
          <binding label="ئ"/>
        </key>
        <key>
          <binding label="ء"/>
        </key>
        <key>
          <binding label="ؤ"/>
        </key>
        <key>
          <binding label="ر"/>
        </key>
        <key>
          <binding label="ى"/>
          <binding shift="true" label="آ"/>
        </key>
        <key>
          <binding label="ة"/>
        </key>
        <key>
          <binding label="و"/>
        </key>
        <key>
          <binding label="ز"/>
        </key>
        <key>
          <binding label="ظ"/>
        </key>

        <key style="special" rtl="true">
          <binding action="backspace"/>
        </key>
      </row>

      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="&#x061F;&#x0663;&#x0662;&#x0661;"/>
        </key>
        
        <key><binding label="ذ"/></key>
        <key id="emailUrlKey"><binding label="،"/></key>

        <key width="stretched">
          <binding action="space"/>
        </key>
        
        <key><binding label="."/></key>
        <key><binding label="ط"/></key>

        <key style="special" width="xx-large" rtl="false" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

  <import file="symbols_ar.xml"/>
</keyboard>

=== maliit/plugins/maliit-keyboard/data/languages/ml_in.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE keyboard SYSTEM 'VirtualKeyboardLayout.dtd'>
<keyboard title="മലയാളം (Malayalam)" version="1.0" autocapitalization="false" catalog="ml_in" language="ml_in">
  <layout type="general">
    <section id="main">
      <row>
        <key>
          <binding label="ൌ"/>
          <binding shift="true" label="ഔ"/>
        </key>
        <key>
          <binding label="ൈ"/>
          <binding shift="true" label="ഐ"/>
        </key>
        <key>
          <binding label="ാ"/>
          <binding shift="true" label="ആ"/>
        </key>
        <key>
          <binding label="ീ"/>
          <binding shift="true" label="ഈ"/>
        </key>
        <key>
          <binding label="ൂ"/>
          <binding shift="true" label="ഊ"/>
        </key>        
	<key>
          <binding label="ബ"/>
          <binding shift="true" label="ഭ"/>
        </key>
        <key>
          <binding label="ഹ"/>
          <binding shift="true" label="ങ"/>
        </key>
        <key>
          <binding label="ഗ"/>
          <binding shift="true" label="ഘ"/>
        </key>
        <key>
          <binding label="ദ"/>
          <binding shift="true" label="ധ"/>
        </key>
        <key>
          <binding label="ജ"/>
          <binding shift="true" label="ഝ"/>
        </key>
        <key>
          <binding label="ഡ"/>
          <binding shift="true" label="ഢ"/>
        </key>
      </row>
      <row>
        <key>
          <binding label="ോ"/>
          <binding shift="true" label="ഓ"/>
        </key>
        <key>
          <binding label="േ"/>
          <binding shift="true" label="ഏ"/>
        </key>
        <key>
          <binding label="്"/>
          <binding shift="true" label="അ"/>
        </key>
        <key>
          <binding label="ി"/>
          <binding shift="true" label="ഇ"/>
        </key>
        <key>
          <binding label="ു"/>
          <binding shift="true" label="ഉ"/>
        </key>        
	<key>
          <binding label="പ"/>
          <binding shift="true" label="ഫ"/>
        </key>
        <key>
          <binding label="ര"/>
          <binding shift="true" label="റ"/>
        </key>
        <key>
          <binding label="ക"/>
          <binding shift="true" label="ഖ"/>
        </key>
        <key>
          <binding label="ത"/>
          <binding shift="true" label="ഥ"/>
        </key>
        <key>
          <binding label="ച"/>
          <binding shift="true" label="ഛ"/>
        </key>
        <key>
          <binding label="ട"/>
          <binding shift="true" label="ഠ"/>
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="shift"/>
        </key>
        <key>
          <binding label="െ"/>
          <binding shift="true" label="എ"/>
        </key>
        <key>
          <binding label="ം"/>
          <binding shift="true" label="ൃ"/>
        </key>
        <key>
          <binding label="മ"/>
          <binding shift="true" label="ണ"/>
        </key>
        <key>
          <binding label="ന"/>
          <binding shift="true" label="ഞ"/>
        </key>
        <key>
          <binding label="വ"/>
          <binding shift="true" label="ഴ"/>
        </key>
        <key>
          <binding label="ല"/>
          <binding shift="true" label="ള"/>
        </key>
        <key>
          <binding label="സ"/>
          <binding shift="true" label="ശ"/>
        </key>
        <key>
          <binding label="യ"/>
          <binding shift="true" label="ഷ"/>
        </key>
        <key style="special" width="x-large">
          <binding action="backspace"/>
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="+!="/>
        </key>
        <key>
          <binding label="ൊ"/>
          <binding shift="true" label="ഒ"/>
        </key>
        <key>
          <binding label="ന്‍"/>
          <binding shift="true" label="ണ്‍"/>
        </key>
        <key style="special" width="stretched">
          <binding action="space"/>
        </key>
        <key>
          <binding label="ല്‍"/>
          <binding shift="true" label="ള്‍"/>
        </key>
        <key>
          <binding label="ര്‍"/>
          <binding shift="true" label="ല്‍"/>
        </key>
        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
    <section id="symbols0" type="non-sloppy">
      <row>
        <key>
          <binding label="൧"/>
          <binding shift="true" label="1"/>
       </key>
        <key>
          <binding label="൨"/>
          <binding shift="true" label="2"/>
        </key>
        <key>
          <binding label="൩"/>
          <binding shift="true" label="3"/>
        </key>
        <key>
          <binding label="൪"/>
          <binding shift="true" label="4"/>
        </key>
        <key>
          <binding label="൫"/>
          <binding shift="true" label="5"/>
        </key>
        <key>
          <binding label="൬"/>
          <binding shift="true" label="6"/>
        </key>
        <key>
          <binding label="൭"/>
          <binding shift="true" label="7 "/>
        </key>
        <key>
          <binding label="൮"/>
          <binding shift="true" label="8"/>
        </key>
        <key>
          <binding label="൯"/>
          <binding shift="true" label="9"/>
        </key>
        <key>
          <binding label="൦"/>
          <binding shift="true" label="0"/>
        </key>
        <key>
          <binding label="_"/>
        </key>
      </row>
      <row>
        <key>
          <binding label="൰"/>
        </key>
        <key>
          <binding label="൱"/>
        </key>
        <key>
          <binding label="൲"/>
        </key>
        <key>
          <binding label="൳"/>
        </key>
        <key>
          <binding label="൴"/>
        </key>
        <key>
          <binding label="?"/>
        </key>
        <key>
          <binding label=","/>
        </key>
        <key>
          <binding label="."/>
        </key>
        <key>
          <binding label="ഃ"/>
          <binding shift="true" label="&#x0022;"/>
        </key>
        <key>
          <binding label="ഋ"/>
          <binding shift="true" label="&#x0027;"/>
        </key>
        <key>
          <binding label="@"/>
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="shift"/>
        </key>
        <key>
          <binding label="%"/>
        </key>
        <key>
          <binding label="#"/>
        </key>
        <key>
          <binding label="("/>
        </key>
        <key>
          <binding label=")"/>
        </key>
        <key>
          <binding label="!"/>
        </key>
        <key>
          <binding label="£"/>
        </key>
        <key>
          <binding label="$"/>
        </key>
        <key>
          <binding label="₹"/>
        </key>
        <key style="special" width="x-large">
          <binding action="backspace"/>
        </key>
      </row>
      <row>
        <key style="special" width="x-large">
          <binding action="sym" label="അ"/>
        </key>
        <key>
          <binding label="="/>
         </key>
        <key>
          <binding label="+"/>
        </key>
        <key style="special" width="stretched">
          <binding action="space"/>
        </key>
        <key>
          <binding label="-"/>
        </key>
        <key>
          <binding label="*"/>
        </key>
        <key style="special" width="x-large" id="actionKey">
          <binding action="return"/>
        </key>
      </row>
    </section>
  </layout>

</keyboard>
